name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo registry and build artifacts
      uses: Swatinem/rust-cache@v2

    - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        echo "$HOME/.config/.foundry/bin" >> $GITHUB_PATH
        source ~/.bashrc
        cat ~/.bashrc
        env
        ls $HOME/.config/.foundry/bin
        $HOME/.config/.foundry/bin/foundryup

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
